version: '3.9'
services:
  web:
    build: .
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - redis
    networks:
      - app_network

  worker:
    build: .
    command: celery -A src worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
